# Generated by Django 3.2.12 on 2023-05-02 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230502_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='mainapp.job'),
        ),
        migrations.AlterField(
            model_name='video',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Videos', to='mainapp.event'),
        ),
    ]
